[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.10.0"
rrplug = { workspace = true }
windows-sys = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }
